apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pomerium
          image: pomerium/ingress-controller:main@sha256:803f08c7990f44fe1f79f00c8c4b58b45a4909938171614f337fe1c86c45698c
          imagePullPolicy: Always
