apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: pomerium
          image: pomerium/ingress-controller:main@sha256:7265cda531ba257579487b057968925bd5c68a2bf40acfd9c85c0f0346bbc76a
          imagePullPolicy: Always
