apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: pomerium-stress-test
      containers:
      - name: stress-test
        args:
          - "stress-test"
        image: pomerium/ingress-controller:main@sha256:7265cda531ba257579487b057968925bd5c68a2bf40acfd9c85c0f0346bbc76a
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: SERVICE_NAME
            value: "stress-test-echo"
          - name: SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: SERVICE_PORT_NAMES
            value: "echo1,echo2"
          - name: CONTAINER_PORT_NUMBERS
            value: "8081,8082"
          - name: INGRESS_CLASS
            value: "pomerium"
          - name: INGRESS_DOMAIN
            valueFrom:
              configMapKeyRef:
                optional: false
                name: stress-test
                key: ingress-domain
          - name: INGRESS_COUNT
            valueFrom:
              configMapKeyRef:
                optional: false
                name: stress-test
                key: ingress-count
          - name: READINESS_TIMEOUT
            valueFrom:
              configMapKeyRef:
                optional: false
                name: stress-test
                key: readiness-timeout
        ports:
        - containerPort: 8081
          name: echo1
        - containerPort: 8082
          name: echo2
