name: Backport
permissions:
  contents: read
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.BACKPORT_APP_APPID }}
          private_key: ${{ secrets.BACKPORT_APP_PRIVATE_KEY }}

      - name: Backport
        uses: pomerium/backport@98051d9820d4bc9902716f750f5866114c08b7e4
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          title_template: "{{originalTitle}}"
          copy_original_labels: true
