name: Docs
on:
  push:
    branches:
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: actions/setup-go@5a083d0e9a84784eb32078397cf5459adecb4c40
        with:
          go-version: 1.23.x

      - name: generate docs
        run: make docs

      - name: Create pull request in the documentations repo
        env:
          API_TOKEN_GITHUB: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          USER_EMAIL: ${{ github.event.pusher.email }}
          USER_NAME: ${{ github.event.pusher.name }}
        run: scripts/open-docs-pull-request.sh
