name: Docs
on:
  push:
    branches:
      - main

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: 1.23.x

      - name: generate docs
        run: make docs

      - name: Create pull request in the documentations repo
        env:
          API_TOKEN_GITHUB: ${{ secrets.APPARITOR_GITHUB_TOKEN }}
          USER_EMAIL: ${{ github.event.pusher.email }}
          USER_NAME: ${{ github.event.pusher.name }}
        run: scripts/open-docs-pull-request.sh
